### ISSUE TITLE
Inductive Datasets

### ISSUE THREAD

**Issue by vthost** [kkteru/grail#1]
Hi, in the paper it says the following, but we observed several overlapping entities (e.g., /m/080knyg in fb237_v1_ind). Are we maybe missing steps in the data processing, or could you please detail what you mean by inductive setting?

"F. Inductive Graph Generation
The inductive train and test graphs examined in this paper do not have overlapping entities."

Thank you already!

**Comment by kkteru** [comment]
Hi!

Quoting from the paper:
`Each of our datasets consists of a pair of graphs: train-graph (fb237_v1) and ind-test-graph (fb237_v1_ind). These two graphs  (i) have a disjoint set of entities, and (ii) train-graph contains all the relations present in ind-test-graph.`

To elaborate, there will be no overlapping entities between `fb237_v1` and `fb237_v1_ind`. The models are trained on `fb237_v1` and tested on `fb237_v1_ind` in the inductive setting. Following is an illustrative example:

![image](https://user-images.githubusercontent.com/7015292/86963304-4cd87080-c132-11ea-81f2-b273e0d75990.png)

So, the model wouldn't have seen `S. Curry`, `Ayesha`, and `CA` during training. But an inductive model should still be able to make an accurate prediction by learning the relational rule from the train-graph. Hope that clarifies your question.

This is in fact a rather confusing point. We will try to clarify further in the paper. Thanks for your question!

**Comment by vthost** [comment]
Thank you for the fast reply!
It now makes sense. Maybe you should not call edges from the inductive test graph train edges. To me, it seems that they are not used to train the model, but rather additional input at test time.
